language: python
python: 
  - "3.9"

services:
  - docker

before_install:
  - echo $DOCKER_PASSWORD | docker login --username "modo24" --password-stdin
  # - docker login -u modo24 --password "c90e7f1d-d1a7-4fd4-8da6-ff822bf3d5ab " 

before_script: pip install docker-compose

script:
  - docker-compose run app sh -c "python manage.py test && flake8"


